# Lines beginning with a # are comments, and are only included for
# illustration. These comments are overkill for most inventory files.

# Local control node
[local]
# fill in IP address after provisioning

# Managed nodes
[nodes]
# fill in IP addresses after provisioning
