---
# non-sensitive data

ansible_user: "{{ vault_ansible_user }}"
ansible_port: 5678
ansible_connection: ssh

# sensitive data

ansible_password: "{{ vault_ansible_password }}"
home_ip: "{{ vault_home_ip }}"
tailscale_auth_key: "{{ vault_tailscale_auth_key }}"
oci_config: "{{ vault_oci_config }}"
oci_cli_rc: "{{ vault_oci_cli_rc }}"
opencode_config: "{{ vault_opencode_config }}"
