#SPDX-License-Identifier: MIT-0
---

# Disable Docker after install to avoid conflict

- name: Disable system-wide Docker
  ansible.builtin.systemd_service:
    name: " {{ item }}"
    enabled: false
    state: stopped
    masked: true
  loop:
    - docker.service
    - docker.socket



# handlers file for docker-engine-rootless
