# Lines beginning with a # are comments, and are only included for
# illustration. These comments are overkill for most inventory files.

# Group 'local' with only acer server
[local]
192.168.55.200  

# Variables that will be applied to all servers
#[multi:vars]
#ansible_user=rizky
#static_ip_only=192.168.55.104/24, 192.168.55.106/24

