---
- name: Install packages on server
  hosts: all
  become: true

  tasks:
    - name: Update apt cache and install packages
      ansible.builtin.apt:
        name:
          - git
          - ansible
          - ca-certificates
        state: present
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"
